# Generated by Django 4.2 on 2024-08-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, verbose_name='Вид лечения')),
                ('description', models.TextField(verbose_name='Описсание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='service_photo/', verbose_name='Фото вида лечения')),
            ],
            options={
                'verbose_name': 'Вид лечения',
                'verbose_name_plural': 'Виды лечения',
            },
        ),
        migrations.AddField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors_photo/', verbose_name='Фото врача'),
        ),
    ]
