# Generated by Django 4.2 on 2024-08-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0002_services_doctors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentistry.services', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
