# Generated by Django 4.2 on 2024-08-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0004_doctors_description_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
