# Generated by Django 4.2 on 2024-08-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата отправки сообщения'),
        ),
    ]
