# Generated by Django 4.2 on 2024-08-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='slug',
        ),
    ]
