# Generated by Django 4.2 on 2024-08-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_articles_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='created_at',
        ),
    ]
